on: [push]
name: AzureLogin

jobs:

  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
    -  uses: actions/checkout@v1     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CRED }}
        
    - name: azure cli script
      uses: azure/CLI@v1
      with:
         azcliversion: 2.30.0
         inlinescript: az deployment group create  --resource-group Res_Grp --template-file ./template.bicep --parameters adminPassword=${{ secrets.ADMINPASSWORD}}
